#!/bin/sh
# package-macos.sh — assemble dist/PocketCOM.app and a distributable .dmg from
# already-built artifacts:
#   dist/pocketcom-main.{js,pak}               (npm run build)
#   host/macos/target/release/pocketcom-host   (cargo build --release)
#
# The host binary only takes config from argv + POCKETJS_DIST (the
# CARGO_MANIFEST_DIR path baked in at compile time is meaningless on end-user
# machines), so the bundle is: a launcher script (CFBundleExecutable) that sets
# POCKETJS_DIST and execs the binary with plan-derived flags (same derivation
# as tools/dev.mjs), the binary itself, and the two dist files (they are
# self-contained: i18n, glyph atlas and styles all live in the .pak).
#
# Signed ad-hoc only (no Apple Developer account / notarization): the first
# launch needs right-click -> Open or `xattr -cr` on Gatekeeper-blocked
# bundles. No App Sandbox, so serial/socket IO needs no entitlements.
#
# Usage: tools/package-macos.sh   (VERSION=x.y.z overrides the bundle version)
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
js="$root/dist/pocketcom-main.js"
pak="$root/dist/pocketcom-main.pak"
host_bin="$root/host/macos/target/release/pocketcom-host"
plan="$root/.pocket/macos-app/plan.json"

for f in "$js" "$pak" "$host_bin"; do
  if [ ! -f "$f" ]; then
    echo "error: missing $f — build the artifacts first:" >&2
    echo "  npm run build && cargo build --locked --release --manifest-path host/macos/Cargo.toml" >&2
    exit 1
  fi
done

# Bundle version: VERSION env wins (CI passes the tag without its v prefix),
# else package.json's version.
version="${VERSION:-$(POCKETCOM_PKG="$root/package.json" node -p 'require(process.env.POCKETCOM_PKG).version')}"
version="${version#v}"

# Host flags derived from the plan generated by `npm run build` (same logic as
# tools/dev.mjs); fall back to the current plan's defaults when absent. The
# node program emits shell-quoted args; it must run from a file/pipe (a heredoc
# inside "$( )" does not parse in sh/bash).
flags_tmp="$(mktemp "${TMPDIR:-/tmp}/pocketcom-flags.XXXXXX")"
trap 'rm -f "$flags_tmp"' EXIT
POCKETCOM_PLAN="$plan" node - > "$flags_tmp" <<'NODE'
const fs = require("fs");
let plan = null;
try {
  plan = JSON.parse(fs.readFileSync(process.env.POCKETCOM_PLAN, "utf8"));
} catch {}
let args;
if (plan && plan.app && plan.viewport) {
  args = [
    "--app", plan.app.output,
    "--title", plan.app.title,
    "--viewport", `${plan.viewport.logical[0]}x${plan.viewport.logical[1]}`,
    "--density", String(plan.viewport.rasterDensity),
    ...(plan.viewport.policy === "fixed" ? ["--fixed"] : []),
    ...(plan.features["text.layout.native"] ? ["--native-text"] : []),
    ...(plan.companions?.length ? ["--companions", plan.companions.join(",")] : []),
    ...(plan.companions?.length ? ["--editor"] : []),
  ];
} else {
  args = ["--app", "pocketcom-main", "--title", "PocketCOM", "--viewport",
          "960x640", "--density", "2", "--native-text", "--companions",
          "pocketcom", "--editor"];
}
const shq = (s) => "'" + String(s).replace(/'/g, `'\\''`) + "'";
console.log(args.map(shq).join(" "));
NODE
flags="$(cat "$flags_tmp")"

app="$root/dist/PocketCOM.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" \
         "$app/Contents/Resources/dist" \
         "$app/Contents/Resources/en.lproj" \
         "$app/Contents/Resources/zh-Hans.lproj"

printf 'APPL????' > "$app/Contents/PkgInfo"

# NSLocalNetworkUsageDescription pre-fills the macOS 15+ local network privacy
# prompt for the SPEC'd future TCP/UDP/WebSocket connections to LAN devices;
# 127.0.0.1 listeners (the project's security default) never trigger it.
cat > "$app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleDisplayName</key><string>PocketCOM</string>
  <key>CFBundleExecutable</key><string>PocketCOM</string>
  <key>CFBundleIdentifier</key><string>dev.kaidegit.pocketcom</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>PocketCOM</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$version</string>
  <key>CFBundleVersion</key><string>$version</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
  <key>LSMinimumSystemVersion</key><string>12.3</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSLocalNetworkUsageDescription</key><string>PocketCOM needs local network access to reach serial-over-IP devices and to debug TCP/UDP/WebSocket endpoints on your network.</string>
  <key>NSPrincipalClass</key><string>NSApplication</string>
</dict>
</plist>
EOF

printf '"NSLocalNetworkUsageDescription" = "PocketCOM needs local network access to reach serial-over-IP devices and to debug TCP/UDP/WebSocket endpoints on your network.";\n' \
  > "$app/Contents/Resources/en.lproj/InfoPlist.strings"
printf '"NSLocalNetworkUsageDescription" = "PocketCOM 需要访问本地网络，以连接串口网络设备并调试局域网内的 TCP/UDP/WebSocket 端点。";\n' \
  > "$app/Contents/Resources/zh-Hans.lproj/InfoPlist.strings"

launcher="$app/Contents/MacOS/PocketCOM"
cat > "$launcher" <<EOF
#!/bin/sh
# Generated by tools/package-macos.sh. Flags mirror tools/dev.mjs (derived
# from .pocket/macos-app/plan.json at packaging time).
HERE="\$(cd "\$(dirname "\$0")" && pwd)"
export POCKETJS_DIST="\$HERE/../Resources/dist"
export RUST_LOG="\${RUST_LOG:-info}"
exec "\$HERE/pocketcom-host" $flags
EOF
chmod +x "$launcher"

cp "$host_bin" "$app/Contents/MacOS/pocketcom-host"
cp "$js" "$pak" "$app/Contents/Resources/dist/"

plutil -lint "$app/Contents/Info.plist"
codesign --force --deep --sign - "$app"
codesign --verify --deep --strict "$app"

staging="$root/dist/.dmg-staging"
dmg="$root/dist/PocketCOM-$version-macos-arm64.dmg"
rm -rf "$staging" "$dmg"
mkdir -p "$staging"
cp -R "$app" "$staging/"
ln -s /Applications "$staging/Applications"
hdiutil create -volname PocketCOM -srcfolder "$staging" -ov -format UDZO "$dmg"
rm -rf "$staging"

echo "packed: $app"
echo "packed: $dmg"
